<a href="https://colab.research.google.com/github/Muriloviskexe/Python/blob/main/Deque_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from collections import deque

meu_deque = deque()

meu_deque.append(1)
meu_deque.append(2)
meu_deque.append(3)
print(meu_deque)

meu_deque.appendleft(21)
print(meu_deque)

meu_deque.pop()
print(meu_deque)

meu_deque.popleft()
print(meu_deque)

deque([1, 2, 3])
deque([21, 1, 2, 3])
deque([21, 1, 2])
deque([1, 2])


In [14]:
from collections import deque

meu_deque = deque(maxlen = 3)

meu_deque.append(1)
meu_deque.append(2)
meu_deque.append(3)
print(meu_deque)

meu_deque.append(4)
print(meu_deque)

meu_deque.appendleft(0)
print(meu_deque)

deque([1, 2, 3], maxlen=3)
deque([2, 3, 4], maxlen=3)
deque([0, 2, 3], maxlen=3)


In [17]:
from collections import deque

meu_deque = ([1, 2, 3, 4, 5])

meu_deque.reverse()
print(meu_deque)

[5, 4, 3, 2, 1]


In [19]:
from collections import deque

meu_deque = deque([1, 2, 3, 4, 5])

meu_deque.rotate(2)
print(meu_deque)

meu_deque.rotate(3)
print(meu_deque)

deque([4, 5, 1, 2, 3])
deque([1, 2, 3, 4, 5])


In [22]:
from collections import deque

deque = deque({'a', 'b', 'c', 'd'})

print(meu_deque[0])
print(meu_deque[-1])

meu_deque[1] = 'x'
print(meu_deque)

1
5
deque([1, 'x', 3, 4, 5])


In [26]:
from collections import deque

deque2 = deque([10, 20, 30, 40, 50])

for elemento in deque2:
  print(elemento)

10
20
30
40
50


In [30]:
from collections import deque

pilha = deque()
pilha.append('a')
pilha.append('b')
pilha.append('c')
pilha.append('d')
print(pilha.pop())

fila = deque()
fila.append('a')
fila.append('b')
fila.append('c')
fila.append('d')
print(fila.popleft())

d
a


In [32]:
from collections import deque

def inserir_com_prioridade (deque, elemento):
  if not deque or elemento >= deque[-1]:
    deque.append(elemento)
  else:
    for i in range(len(deque)):
      if elemento < deque[i]:
        deque.insert(i, elemento)
        break

fila_prioridade = deque()

inserir_com_prioridade(fila_prioridade, 3)
inserir_com_prioridade(fila_prioridade, 1)
inserir_com_prioridade(fila_prioridade, 2)
inserir_com_prioridade(fila_prioridade, 5)

print(fila_prioridade)

deque([1, 2, 3, 5])


In [35]:
import array as arr

meu_array = arr.array('i', [1, 2, 3, 4, 5])

print(meu_array)

print(meu_array[0])
print(meu_array[3])

array('i', [1, 2, 3, 4, 5])
1
4


In [41]:
import array as arr

meu_array = arr.array('i', [1, 2, 3])

meu_array.append(5)
print(meu_array)


meu_array.insert(1, 10)
print(meu_array)

meu_array.remove(10)
print(meu_array)

meu_array.pop()
print(meu_array)

array('i', [1, 2, 3, 5])
array('i', [1, 10, 2, 3, 5])
array('i', [1, 2, 3, 5])
array('i', [1, 2, 3])


In [44]:
import array as arr

meu_array = arr.array('i', [1, 2, 3, 4, 5])

for elemento in meu_array:
  print(elemento)


1
2
3
4
5


In [48]:
import numpy as np

meu_array = np.array([1,2,3,4,5])

print(meu_array)

print(meu_array * 2)
print(meu_array * 3)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 3  6  9 12 15]


In [52]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz)

print(matriz[0, 0])
print(matriz[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6


In [57]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

soma = array1 + array2
print(soma)

produto = array1 * array2
print(produto)

produto_escalar = np.dot(array1, array2)
print(produto_escalar)

[5 7 9]
[ 4 10 18]
32


In [65]:
import numpy as np

zeros_array = np.zeros(5)
print(zeros_array)

uns_array = np.ones(5)
print(uns_array)

linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

random_array = np.random.random(5)
print(random_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0.   2.5  5.   7.5 10. ]
[0.60841505 0.86313453 0.51838892 0.6081852  0.64044967]


In [71]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

matriz = array1.reshape(3, 3)
print(matriz)

linha = matriz.reshape(1, 9)
print(linha)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [74]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filtro = array > 5
print(array[filtro])

filtro_par = array % 2 == 0
print(array[filtro_par])

[6 7 8 9]
[2 4 6 8]


In [75]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

media = np.mean(array)
print(media)

soma = np.sum(array)
print(soma)

desvio_padrao = np.std(array)
print(desvio_padrao)

5.0
45
2.581988897471611
